### ISSUE TITLE
Java Math.random prediction

### ISSUE THREAD

**Issue by TheZ3ro** [alephsecurity/z3-walkthrough#1]
Java's original [Math.random](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#random--) ([Java source](https://developer.classpath.org/doc/java/lang/Math-source.html#line.671)) uses [Random.nextDouble](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextDouble--) ([Java source](https://developer.classpath.org/doc/java/util/Random-source.html#line.369)) under the hood.

I was going through your [break_java_Random.nextLong().py](https://github.com/alephsecurity/z3-walkthrough/blob/master/snippets/break_java_Random.nextLong().py#L4) snippet to port it for `nextDouble` as well but playing with the constants in `make_constraints_next` always end up with a non SAT model.

Can you drive me in the right direction?

The `nextDouble` function seems a pretty straightforward `return (((long) next(26) << 27) + next(27)) / (double) (1L << 53);`

Then support for `nextFloat` could be implemented as well.

**Comment by aronsky** [comment]
Hi, sorry - but this project is currently not maintained.
